### ISSUE TITLE
Right clicking on a player in Multiplayer crashes your client

### ISSUE THREAD

**Issue by Mario90900** [thecodewarrior/Hook-Mod#10]
I have just put together a large modpack that includes Hooked, so starting off it might be cross-mod issues that cause it. But currently in the pack, if you rightclick on another player it ends up crashing you with the crashlog talking about Hooked trying to get a capability marked as non-null, which is null. I have two crashlogs from two friends who had this happen:

https://pastebin.com/zrTHuZxf
https://pastebin.com/wBNJQqdf

I would not be surprised in the least if it was another mod that was causing this, but I can't be sure which mod it is from the changelog. The only other one that shows up seems to be Better With Mods, so if it helps for me to disable that easy breeding thing and try it again, I can easily do so.

**Comment by thecodewarrior** [comment]
Update BetterWithMods, they weren't registering a capability properly in earlier versions.

**Comment by Mario90900** [comment]
Oh alright, thanks for the quick response. I didn't notice BetterWithMods updated so recently, ill get on that right now.

**Comment by Mario90900** [comment]
Even after updating the server to the newest version of Better With Mods, it still appears that right clicking on another player crashes you. Is there anything you can do on your end to work around this issue, or is it all on them?

**Comment by thecodewarrior** [comment]
I _could_ fix it on my end, but they’re violating the API and my mod by
accident is kind of a canary in the coal mine. This could cause all sorts
of problems, many more subtle and difficult to debug, but since kotlin
enforces nullability my mod crashes when that is violated. Yes it could be
fixed, but shouldn’t, and yes, it’s all on them.
