### ISSUE TITLE
Unable to use hook after switching dimensions

### ISSUE THREAD

**Issue by clragon** [thecodewarrior/Hook-Mod#11]
After switching to another dimension, I'm not able to use my hook and have to reequip it every time. 

It's highly annoying.
Can this be fixed?

kind regards.

**Comment by thecodewarrior** [comment]
Can you give me any more details about your setup? e.g. modpack/modlist and configs if you’ve modified them. Also, i need to know if you can reliably reproduce the issue and the steps required to do so. Logs would be helpful as well.

**Comment by clragon** [comment]
#### Server Log: [latest.log](https://github.com/thecodewarrior/Hooked/files/2243262/latest.log)
#### Modlist: [modlist.txt](https://github.com/thecodewarrior/Hooked/files/2243269/modlist.txt)


The issue is reproducable 100% of the time.

Switching dimension trough any method provided will make me unable to use the hook and I need to take it out of the bauble slot and put it back in to use it again.

#### **Steps:**
1. aquire any hook
1. equip in any bauble slot 
1. switch to a different dimension

#### **Result**: hook is now unusable and you need to take it out of the slot and put it back

I can send you any of the configs if you tell me which mod(s) you need.

**Comment by clragon** [comment]
[Updated my comment with requested information]

**Comment by NewtonAppolonius** [comment]
Just to add that I see this behaviour as well.
Tested it in my test instance, standard 12.2.2 vanilla with just Hooked installed, and the same behaviour is seen.
