### ISSUE TITLE
Relogging with hook in bauble slot causes hotkey to stop working

### ISSUE THREAD

**Issue by terrapin47** [thecodewarrior/Hook-Mod#13]
The grappling hook hotkey will not work upon relog until you remove and replace it back in the bauble slot.

This also happens when using tombmanygraves after a death, upon recovering your grave when the item is automatically placed back in the bauble slot - the hotkey will fail to work until you replace it back in the slot.

**Comment by thecodewarrior** [comment]
This will be fixed in the next version. I should be able to release it tomorrow.
