### ISSUE TITLE
[Feature request] Entity hooking

### ISSUE THREAD

**Issue by xt9** [thecodewarrior/Hook-Mod#14]
I've thought about this before while playing with Hooked, but once I saw the [gameplay reveal for the new Doom game (WARNING: Gore)](https://youtu.be/CGq8Ee2gOe4?t=424) I was reminded that this is a feature that would be really cool for hooked.

I really love hooked as a creative flight alternative, and it really helps making combat movement more interesting (and non-trivial as opposed to creative flight). 

I think stuff like hooking a Ghast or a Blaze would feel pretty awesome and would be a nice addition to the mod.

**Comment by thecodewarrior** [comment]
That's a great idea, however I like to keep my mods small and very limited in scope, doing one thing and doing it well. Hooked is a mod about player movement, so I think grappling and pulling in entities is a bit outside of its scope, however that might be cool as a separate mod.
