### ISSUE TITLE
Crash on World Enter with references to aether legacy?

### ISSUE THREAD

**Issue by Darkmega18** [thecodewarrior/Hook-Mod#29]
Forge: forge-1.12.2-14.23.5.2815.jar
Hooked: hooked-1.0.3.jar 
Aether Legacy (cause it makes references to it): aether_legacy-1.12.2-v1.4.0.jar

was updating all my mods for my modpack, Transcendence, which is long over due an update due to myself burning out for a while. :V But after managing to make the game load and test running a brand new world using quark realistic and starting chest in creative mode this crash happened that makes reference to aether legacy api and some stuff figured I'd report it to both places. 

The crash actually created two versions of itself in the crash logs folder too. A client and a server version.
I've posted it to aether legacy's issues also and will cross link it.

Here (client):
https://pastebin.com/mrM1sqYu

and Here (server):
https://pastebin.com/SkyRfrQ2

Loading the game without aether legacy (after exploding once due to my configured tough as nails configs :V) allows the game to run, however aether legacy and hooked are kinda required as part of the quests  of my modpack so I can't update without it this fixed, so please take a look.

(link to aether legacy's side of my report) https://github.com/Modding-Legacy/Aether-Legacy/issues/384

**Comment by thecodewarrior** [comment]
This is aether's problem. This is now the fourth time one of my mods has crashed like this, identifying a problem in someone else's mod. Basically their mod is broken and if any two mods are broken the same way they likely will crash with a far less helpful exception message.
