### ISSUE TITLE
That hooks comes from where?!?

### ISSUE THREAD

**Issue by NJM1564** [thecodewarrior/Hook-Mod#31]
Why is the hook coming from between the legs while viewing steve in third person!!!

**Comment by thecodewarrior** [comment]
The idea is it's tied around your waist. This is both visual and means that your head isn't smashed up against the hook on the wall.

**Comment by NJM1564** [comment]
Might want to add a bit of something there on the belt so it doesn't look like a extendomatic shlong.

**Comment by thecodewarrior** [comment]
If you want to submit a pull request I'd be happy to take a look and merge it, this just isn't going to be a priority.
