### ISSUE TITLE
Hooked with Gravestone Mods

### ISSUE THREAD

**Issue by hapatel96** [thecodewarrior/Hook-Mod#38]
Hi guys I was trying to see if this was a feature or if it is a bug. I died in the nether and lost my diamond hook so I used my old iron to get back to my gravestone. But when I clicked the gravestone to retrieve everything my diamond hook disappeared. This has happened multiple times with different variations of the hook. So I was wondering if this is intended or a bug with the gravestones.

**Comment by thecodewarrior** [comment]
That's on the gravestone mod. If the gravestone mod is built poorly it may freak out trying to restore the hook into its old slot, and there's nothing I can really do to fix that on my end.

If the gravestone mod is on GitHub I'd see about submitting an issue regarding restoring baubles. If your inventory ended up 100% full after the restore that would be valuable information for tracing the bug.

Thanks for taking the time to report it though, most people just ignore issues so mod authors never find out about them. :)
