### ISSUE TITLE
Crash with Better with Mods

### ISSUE THREAD

**Issue by angelnc1989** [thecodewarrior/Hook-Mod#6]
[Crash report](https://pastebin.com/bKPpWG8W)
Happens when entering a world

**Comment by thecodewarrior** [comment]
It's a problem with BetterWithMods. Just submitted an issue: https://gitlab.com/BetterWithMods/BetterWithMods/issues/1069

**Comment by thecodewarrior** [comment]
Can you confirm that this happens with only BWM and Hooked on the latest version of forge?

**Comment by angelnc1989** [comment]
No. And I can't even reproduce the crash in the modpack I originally had the crash. Better with Mods had two updates since though.
