### ISSUE TITLE
Buggy behaviour when equipping/unequipping hooks with other methods than the bauble inventory

### ISSUE THREAD

**Issue by angelnc1989** [thecodewarrior/Hook-Mod#8]
When a hook is equipped from a Bauble Case from Botania or after dying from a grave mod like Tomb Many Graves the hook is not working. It has to be equipped manually from the bauble inventory.  
When a hook is unequipped from the Bauble Case from Botania it still works despite not being equipped.
Also dimension switching sometimes makes the hook stop working. Not really sure what the exact conditions for that are.

**Comment by thecodewarrior** [comment]
I'll look in to the dimension switching, but the bauble inventory stuff is a Baubles bug as far as I know. That's basically the only time the equip/unequip events are fired for the item. I might switch to simply checking each tick if it's changed in order to circumvent that.
